language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

matrix:
 include:
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-7, libhdf5-dev, hdf5-tools, libgsl0-dev, libopenmpi-dev]

install:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
script:
  - python -c "import velociraptor_python_tools"
  - python -c "import velociraptor_python_tools_cython"
